
######## *** 1. Mandatory Testing Config  ###################

test_folder_path: /Users/yarramsettinaresh/Downloads/train/62a4ff872be4ea4a151632b0/  #<test_folder>
output_csv_path: output.csv #output_csv

########  2.(Optional)Inference config  #######################
odo_region_detect_model_path : model/odo_region_best.pt
odo_ocr_model_path: model/odo_ocr_best_model.pth
#######  3.(Optional) Training model optional config ########
base_dataset_path: /Users/yarramsettinaresh/Downloads/train/
odo_detect_model:
  epochs: 50
  imgsz: 640
  batch: 16
  project: yolo_model # logs parent folder name
  name: odometer_lcd  # logs folder name

odo_meter_ocr_mode:
  batch: 16
  epochs: 20
